"""fix: conversion traite et en_commande INTEGER vers BOOLEAN

Revision ID: 149c3e70201b
Revises: f1f2c70d24b0
Create Date: 2026-02-27 09:00:02.445592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149c3e70201b'
down_revision = 'f1f2c70d24b0'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('echeances', schema=None) as batch_op:
        batch_op.alter_column('traite',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='traite::boolean')

    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.alter_column('en_commande',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='en_commande::boolean')
        batch_op.alter_column('traite',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='traite::boolean')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.alter_column('traite',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('en_commande',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('echeances', schema=None) as batch_op:
        batch_op.alter_column('traite',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
