"""add salle model

Revision ID: 3d7332148982
Revises: 
Create Date: 2026-04-20 23:01:07.311391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d7332148982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('echeances', schema=None) as batch_op:
        batch_op.alter_column('traite',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               postgresql_using='traite::integer',
               existing_nullable=True)

    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.alter_column('en_commande',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               postgresql_using='en_commande::integer',
               existing_nullable=True)
        batch_op.alter_column('traite',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               postgresql_using='traite::integer',
               existing_nullable=True)
        batch_op.drop_column('capacite_initiale')
        batch_op.drop_column('niveau_actuel')
        batch_op.drop_column('type_objet')
        batch_op.drop_column('seuil_pourcentage')
        batch_op.drop_column('unite')
        batch_op.drop_column('niveau_requis')
        batch_op.drop_column('is_cmr')

    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('panier_items_salle_id_fkey'), type_='foreignkey')
        batch_op.drop_column('recurrence_data')
        batch_op.drop_column('salle_id')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reservations_recurrence_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reservations_salle_id_fkey'), type_='foreignkey')
        batch_op.drop_column('recurrence_id')
        batch_op.drop_column('salle_id')

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_column('niveau_enseignement')
        batch_op.drop_column('statut_compte')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut_compte', sa.VARCHAR(length=20), server_default=sa.text("'actif'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('niveau_enseignement', sa.VARCHAR(length=50), server_default=sa.text("'lycee'::character varying"), autoincrement=False, nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recurrence_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('reservations_salle_id_fkey'), 'salles', ['salle_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reservations_recurrence_id_fkey'), 'reservation_recurrences', ['recurrence_id'], ['id'])

    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recurrence_data', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('panier_items_salle_id_fkey'), 'salles', ['salle_id'], ['id'])

    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cmr', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('niveau_requis', sa.VARCHAR(length=50), server_default=sa.text("'tous'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unite', sa.VARCHAR(length=10), server_default=sa.text("'unite'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seuil_pourcentage', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_objet', sa.VARCHAR(length=20), server_default=sa.text("'materiel'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('niveau_actuel', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacite_initiale', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
        batch_op.alter_column('traite',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('en_commande',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('echeances', schema=None) as batch_op:
        batch_op.alter_column('traite',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('lu', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], name=op.f('notifications_etablissement_id_fkey')),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('notifications_utilisateur_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('documents_reglementaires',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('type_doc', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fichier_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_upload', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fichier_pdf', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], name=op.f('documents_reglementaires_etablissement_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_reglementaires_pkey'))
    )
    op.create_table('inventaires_archives',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('date_archive', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fichier_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nb_objets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fichier_pdf', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], name=op.f('inventaires_archives_etablissement_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventaires_archives_pkey'))
    )
    # ### end Alembic commands ###
