"""add salle model and reservation salle_id

Revision ID: 695dd1b7adc0
Revises: 149c3e70201b
Create Date: 2026-03-06 18:20:34.311086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695dd1b7adc0'
down_revision = '149c3e70201b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salles', schema=None) as batch_op:
        batch_op.create_index('idx_salles_etablissement', ['etablissement_id'], unique=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'salles', ['salle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salle_id')

    with op.batch_alter_table('salles', schema=None) as batch_op:
        batch_op.drop_index('idx_salles_etablissement')

    op.drop_table('salles')
    # ### end Alembic commands ###
