"""fix_type_objet_objet_to_materiel

Revision ID: 6b333981fdc4
Revises: ce93e1baf8d7
Create Date: 2026-03-27 21:30:03.871488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b333981fdc4'
down_revision = 'ce93e1baf8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
