"""ajout niveau_enseignement utilisateur

Revision ID: 7b2f1a937c95
Revises: 3d7332148982
Create Date: 2026-05-01 23:18:58.499553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2f1a937c95'
down_revision = '3d7332148982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_objet', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('unite', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('capacite_initiale', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('niveau_actuel', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seuil_pourcentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('niveau_requis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_cmr', sa.Boolean(), nullable=True))

    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'salles', ['salle_id'], ['id'])

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'reservation_recurrences', ['recurrence_id'], ['id'])
        batch_op.create_foreign_key(None, 'salles', ['salle_id'], ['id'])

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau_enseignement', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('statut_compte', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_column('statut_compte')
        batch_op.drop_column('niveau_enseignement')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.drop_column('is_cmr')
        batch_op.drop_column('niveau_requis')
        batch_op.drop_column('seuil_pourcentage')
        batch_op.drop_column('niveau_actuel')
        batch_op.drop_column('capacite_initiale')
        batch_op.drop_column('unite')
        batch_op.drop_column('type_objet')

    # ### end Alembic commands ###
