"""add salle_id to panier_items

Revision ID: 98a2e6bed7a6
Revises: 695dd1b7adc0
Create Date: 2026-03-07 11:16:52.337938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a2e6bed7a6'
down_revision = '695dd1b7adc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'salles', ['salle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salle_id')

    # ### end Alembic commands ###
