"""add reservation recurrence

Revision ID: 9f8a6423c433
Revises: 98a2e6bed7a6
Create Date: 2026-03-07 17:59:40.230778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8a6423c433'
down_revision = '98a2e6bed7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_recurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('type_recurrence', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('nb_occurrences', sa.Integer(), nullable=True),
    sa.Column('heure_debut', sa.String(length=5), nullable=False),
    sa.Column('heure_fin', sa.String(length=5), nullable=False),
    sa.Column('salle_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'reservation_recurrences', ['recurrence_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recurrence_id')

    op.drop_table('reservation_recurrences')
    # ### end Alembic commands ###
