"""add fichier_pdf to documents_reglementaires

Revision ID: bce368a64328
Revises: fe06e1d66966
Create Date: 2026-04-11 22:37:42.904721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce368a64328'
down_revision = 'fe06e1d66966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_reglementaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fichier_pdf', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_reglementaires', schema=None) as batch_op:
        batch_op.drop_column('fichier_pdf')

    # ### end Alembic commands ###
