"""add recurrence_data to panier_items

Revision ID: ce93e1baf8d7
Revises: 9f8a6423c433
Create Date: 2026-03-07 23:17:40.965653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce93e1baf8d7'
down_revision = '9f8a6423c433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.drop_column('recurrence_data')

    # ### end Alembic commands ###
