"""Ajout CMR et Documents

Revision ID: e434aae30f83
Revises: 7cbf1eb66527
Create Date: 2026-01-21 18:28:05.762942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e434aae30f83'
down_revision = '7cbf1eb66527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cmr', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.drop_column('is_cmr')

    # ### end Alembic commands ###
