"""init: création complète du schéma

Revision ID: f1f2c70d24b0
Revises: 
Create Date: 2026-02-25 00:40:31.311795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f2c70d24b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code_invitation', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_invitation')
    )
    op.create_table('armoires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('montant_initial', sa.Float(), nullable=True),
    sa.Column('cloture', sa.Boolean(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_reglementaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('type_doc', sa.String(length=50), nullable=True),
    sa.Column('fichier_url', sa.String(length=255), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('echeances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=100), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('traite', sa.Boolean(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipements_securite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_equipement', sa.String(length=50), nullable=False),
    sa.Column('localisation', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('date_installation', sa.Date(), nullable=True),
    sa.Column('en_service', sa.Boolean(), nullable=True),
    sa.Column('etat_general', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventaires_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=True),
    sa.Column('date_archive', sa.DateTime(), nullable=True),
    sa.Column('fichier_url', sa.String(length=255), nullable=False),
    sa.Column('nb_objets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=50), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('niveau_enseignement', sa.String(length=50), nullable=True),
    sa.Column('statut_compte', sa.String(length=20), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_cible', sa.String(length=50), nullable=False),
    sa.Column('id_enregistrement', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_audit_utilisateur', ['id_utilisateur'], unique=False)

    op.create_table('depenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_depense', sa.Date(), nullable=False),
    sa.Column('contenu', sa.String(length=200), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('est_bon_achat', sa.Boolean(), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objet_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipement_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('periodicite_jours', sa.Integer(), nullable=False),
    sa.Column('type_prestataire', sa.String(length=20), nullable=True),
    sa.Column('date_derniere_action', sa.Date(), nullable=True),
    sa.Column('date_prochaine_action', sa.Date(), nullable=False),
    sa.Column('alerte_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements_securite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_objet', sa.String(length=20), nullable=True),
    sa.Column('unite', sa.String(length=10), nullable=True),
    sa.Column('capacite_initiale', sa.Float(), nullable=True),
    sa.Column('niveau_actuel', sa.Float(), nullable=True),
    sa.Column('seuil_pourcentage', sa.Integer(), nullable=True),
    sa.Column('niveau_requis', sa.String(length=50), nullable=True),
    sa.Column('quantite_physique', sa.Integer(), nullable=True),
    sa.Column('seuil', sa.Integer(), nullable=True),
    sa.Column('date_peremption', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('fds_url', sa.String(length=255), nullable=True),
    sa.Column('is_cmr', sa.Boolean(), nullable=True),
    sa.Column('armoire_id', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('en_commande', sa.Boolean(), nullable=True),
    sa.Column('traite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['armoire_id'], ['armoires.id'], ),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.create_index('idx_objets_etablissement_categorie', ['etablissement_id', 'categorie_id'], unique=False)

    op.create_table('paniers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paniers', schema=None) as batch_op:
        batch_op.create_index('idx_paniers_expiration', ['date_expiration'], unique=False)
        batch_op.create_index('idx_paniers_utilisateur', ['id_utilisateur'], unique=False)

    op.create_table('kit_composants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('objet_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantite > 0', name='check_quantite_positive'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objet_id'], ['objets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_id', 'objet_id', name='_kit_objet_uc')
    )
    with op.batch_alter_table('kit_composants', schema=None) as batch_op:
        batch_op.create_index('idx_kit_composants_kit', ['kit_id'], unique=False)
        batch_op.create_index('idx_kit_composants_objet', ['objet_id'], unique=False)

    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipement_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('date_intervention', sa.Date(), nullable=False),
    sa.Column('operateur', sa.String(length=100), nullable=True),
    sa.Column('resultat', sa.String(length=20), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('fichier_rapport', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements_securite.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panier_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_panier', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('date_reservation', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.String(length=5), nullable=False),
    sa.Column('heure_fin', sa.String(length=5), nullable=False),
    sa.Column('date_ajout', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('quantite > 0', name='check_panier_qte_positive'),
    sa.ForeignKeyConstraint(['id_panier'], ['paniers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.create_index('idx_panier_items_panier', ['id_panier'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.Column('objet_id', sa.Integer(), nullable=True),
    sa.Column('kit_id', sa.Integer(), nullable=True),
    sa.Column('quantite_reservee', sa.Integer(), nullable=False),
    sa.Column('debut_reservation', sa.DateTime(), nullable=False),
    sa.Column('fin_reservation', sa.DateTime(), nullable=False),
    sa.Column('groupe_id', sa.String(length=36), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(objet_id IS NOT NULL AND kit_id IS NULL) OR (objet_id IS NULL AND kit_id IS NOT NULL)', name='check_objet_ou_kit'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['objet_id'], ['objets.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index('idx_reservations_dates', ['debut_reservation', 'fin_reservation'], unique=False)
        batch_op.create_index('idx_reservations_etablissement_statut', ['etablissement_id', 'statut'], unique=False)
        batch_op.create_index('idx_reservations_groupe', ['groupe_id'], unique=False)
        batch_op.create_index('idx_reservations_statut', ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_groupe_id'), ['groupe_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objet_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['objet_id'], ['objets.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_groupe_id'))
        batch_op.drop_index('idx_reservations_statut')
        batch_op.drop_index('idx_reservations_groupe')
        batch_op.drop_index('idx_reservations_etablissement_statut')
        batch_op.drop_index('idx_reservations_dates')

    op.drop_table('reservations')
    with op.batch_alter_table('panier_items', schema=None) as batch_op:
        batch_op.drop_index('idx_panier_items_panier')

    op.drop_table('panier_items')
    op.drop_table('maintenance_logs')
    with op.batch_alter_table('kit_composants', schema=None) as batch_op:
        batch_op.drop_index('idx_kit_composants_objet')
        batch_op.drop_index('idx_kit_composants_kit')

    op.drop_table('kit_composants')
    with op.batch_alter_table('paniers', schema=None) as batch_op:
        batch_op.drop_index('idx_paniers_utilisateur')
        batch_op.drop_index('idx_paniers_expiration')

    op.drop_table('paniers')
    with op.batch_alter_table('objets', schema=None) as batch_op:
        batch_op.drop_index('idx_objets_etablissement_categorie')

    op.drop_table('objets')
    op.drop_table('notifications')
    op.drop_table('maintenance_plans')
    op.drop_table('historique')
    op.drop_table('depenses')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_utilisateur')
        batch_op.drop_index('idx_audit_timestamp')

    op.drop_table('audit_log')
    op.drop_table('utilisateurs')
    op.drop_table('parametres')
    op.drop_table('kits')
    op.drop_table('inventaires_archives')
    op.drop_table('fournisseurs')
    op.drop_table('equipements_securite')
    op.drop_table('echeances')
    op.drop_table('documents_reglementaires')
    op.drop_table('categories')
    op.drop_table('budgets')
    op.drop_table('armoires')
    op.drop_table('etablissements')
    # ### end Alembic commands ###
