"""empty message

Revision ID: fe06e1d66966
Revises: 6b333981fdc4
Create Date: 2026-04-11 20:55:59.248309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe06e1d66966'
down_revision = '6b333981fdc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventaires_archives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fichier_pdf', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventaires_archives', schema=None) as batch_op:
        batch_op.drop_column('fichier_pdf')

    # ### end Alembic commands ###
